### ISSUE TITLE
create a BEQUALI version

### ISSUE THREAD

**Issue by paulgirard** [medialab/reanalyse#50]
create a BeQuali version of the web application.
Not exactly a bug easy to do.

**Comment by paulgirard** [comment]
Explain how to configure SOLR on specific port ?

**Comment by pierrejdlf** [comment]
SOLR_PORT can now be customized within settings.py

**Comment by paulgirard** [comment]
the SOLR JAR file should be renamed by each installation of the software.
Indeed the name of the jar file is used to identify the process to kill when managing SOLR thread from the django app.

**Comment by pierrejdlf** [comment]
solved !
from now on, no need to rename SOLR_JAR file
to identify solr process, we search for the line looking like:

```
"java -jar -Djetty.port=8985 startreanalysesolr.jar"
```

this line is unique, because only one solr instance can run for a given port

note:

we also tried to track solr process PID (seems cleaner), ex.:

```
solrprocess,isnew = SolrProcess.objects.get_or_create(id=0)
p = subprocess.Popen(...,shell=True,...)
solrprocess.pid = str(p.pid)
solrprocess.save()
```

but, since we use "shell=True" ('cause we use Pipe to keep track of logs)
p.pid is the PID of the 'shell' used to launch command, not the PID of the "java -jar..." process
